### ISSUE TITLE
Message list doesn't update without push notifications

### ISSUE THREAD

**Issue by svzi** [iadvize/iadvize-ios-sdk#3]
We noticed that we don’t get any new chat message(s), when we disable push notifications. To be honest, that’s not the way we expect it to work. When a user disables push notifications, the chat should still work and update it's content. The user just shouldn’t get anymore notification messages.

We can’t ask our users to leave the chat and re-enter it, in order to check for new messages. For that reason we would suggest to implement some kind of quick fix like polling every xx seconds. The message list already get's updated when we close and re-open the chat. The backend already knows if a user has enabled or disabled the push notifications. From our point of view, this shouldn’t be hard to implement.

Currently, to be honest, the chat is broken (= useless) without activated push notifications. We need the ability to disable push notifications, but the user should still be able to use messaging.

This issue exists on iOS and Android (see https://github.com/iadvize/iadvize-android-sdk/issues/1) as well.
 
Any updated on this topic would be really much appreciated.

**Comment by alexandrekarst** [comment]
I close this issue since the work on the V2 of our SDK will resolve this issue.
